[package]
name = "custom_types"
version = "0.1.0"
authors = ["Felix Wittwer <dev@felixwittwer.de>"]
# build = "../build.rs"

[dependencies]

[build-dependencies]
# ohua_rust_runtime = { path = "../../" }
