[package]
name = "ohua_macro"
version = "0.1.0"
authors = ["Sebastian Ertel <sebastian.ertel@gmail.com>"]

[dependencies]
ohua_codegen = { path = "../../ohua_codegen/" }
ohua_runtime = { path = "../../ohua_runtime/" }
